suggested_commands = {
    'wakesleep': 'add wakeup and sleep logs',
    'food': 'add food logs',
    'gym': 'add gym logs',
    'yoga': 'add yoga logs',
    'pranayam': 'add pranayam logs',
    'thought': 'add thoughts that came to your mind',
    'taskcompleted': 'add task that you completed sometime back',
    'mywakesleep': 'see wakeup and sleep logs',
    'myfood': 'see food logs',
    'mygym': 'see gym logs',
    'myyoga': 'see yoga logs',
    'mypranayam': 'see pranayam logs',
    'mythought': 'see all thoughts logged',
    'mytaskcompleted': 'see tasks completed',
    'set_timezone': 'set your timezone (important when you change country)',
    'start': 'welcome text',
    'mytimezone': 'see your timezones list',
}